#!/usr/bin/env node
/**
 * Generates SCRIPT_INDEX.md — FLOWER beat scaffold (15 pages beat-01 … beat-15).
 * Run: npm run script-index
 */
const fs = require("fs");
const path = require("path");

const BEAT_COUNT = 15;
const outPath = path.join(__dirname, "../SCRIPT_INDEX.md");

const rows = Array.from({ length: BEAT_COUNT }, (_, i) => {
  const n = i + 1;
  const id = `beat-${String(n).padStart(2, "0")}`;
  return {
    id,
    line: "src/data/script-beat-pages.ts",
    scene: `Beat ${n} (INT. FLOWER HIGH — …)`,
  };
});

const md = `# FLOWER Script Page Index

Generated by \`npm run script-index\`. Beat rows follow \`buildFlowerBeatScriptPages()\` in \`src/data/script-beat-pages.ts\`.

| Page ID | Source | Scene |
|---------|--------|-------|
${rows.map((r) => `| ${r.id} | ${r.line} | ${r.scene} |`).join("\n")}
`;

fs.writeFileSync(outPath, md);
console.log(`Wrote ${outPath} (${rows.length} pages)`);
